Layout/ExtraSpacing:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceAfterNot:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/BlockLength:
  Max: 30
  Severity: warning
Metrics/ClassLength:
  Max: 256
  Severity: warning
Metrics/LineLength:
  Max: 110
  Severity: warning
Metrics/MethodLength:
  Max: 30
  Severity: warning
Naming/BinaryOperatorParameterName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/AccessModifierDeclarations:
  EnforcedStyle: 'inline'
Style/BlockDelimiters:
  EnforcedStyle: 'semantic'
Style/ConditionalAssignment:
  EnforcedStyle: 'assign_inside_condition'
  IncludeTernaryExpressions: false
Style/Documentation:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  AllowedVariables: ['$config', '$db']
  Severity: warning
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Next:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ParenthesesAroundCondition:
  AllowInMultilineConditions: true
  AllowSafeAssignment: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StderrPuts:
  Severity: warning
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
Style/WordArray:
  Enabled: false
